#ifndef AEROC2_TYPE_ID_H_
#define AEROC2_TYPE_ID_H_

enum AEROC2_MSG_TYPE_ID
{
  AEROC2_TYPE_ID_ACTION,
  AEROC2_TYPE_ID_ACTION_ACK,
  AEROC2_TYPE_ID_AIRSPEED,
  AEROC2_TYPE_ID_ALTITUDE,
  AEROC2_TYPE_ID_ATTITUDE,
  AEROC2_TYPE_ID_ATTITUDE_QUATERNION,
  AEROC2_TYPE_ID_BOOT,
  AEROC2_TYPE_ID_DEBUG,
  AEROC2_TYPE_ID_GPS,
  AEROC2_TYPE_ID_GPS_POSITION,
  AEROC2_TYPE_ID_GPS_RAW,
  AEROC2_TYPE_ID_GPS_STATUS,
  AEROC2_TYPE_ID_IMU,
  AEROC2_TYPE_ID_IMU_RAW,
  AEROC2_TYPE_ID_KEEP_ALIVE,
  AEROC2_TYPE_ID_PRESSURE,
  AEROC2_TYPE_ID_STATUS_TEXT
};

#endif  /* AEROC2_TYPE_ID_H_ */
